language: node_js
sudo: false

node_js:
  - "0.10"
  - "0.12"
<<<<<<< HEAD
  - "iojs"
=======
  - "4"
  - "5"
>>>>>>> baf7091c768ba97174848a3c3f1393ec3cf9cba2

after_success:
  - npm run coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | coveralls

notifications:
  email:
    on_success: never
